from __future__ import annotations


EXACT_LOCATION_CONTEXT: dict[str, tuple[str, str]] = {
    "CYOO": ("Toronto FIR", "Canada"),
    "EGTT": ("London FIR", "United Kingdom"),
    "KADW": ("Washington ARTCC / FIR", "United States"),
    "KATL": ("Atlanta ARTCC / FIR", "United States"),
    "KPAM": ("Anchorage Oceanic / FIR", "United States"),
    "KZLC": ("Salt Lake City ARTCC / FIR", "United States"),
    "LLBG": ("Tel Aviv FIR", "Israel"),
    "OIYY": ("Tehran FIR", "Iran"),
    "RJTT": ("Tokyo FIR", "Japan"),
    "VOBZ": ("Chennai FIR", "India"),
}


PREFIX_LOCATION_CONTEXT: tuple[tuple[str, str, str], ...] = (
    ("K", "United States domestic ARTCC / FIR system", "United States"),
    ("P", "United States Pacific ARTCC / FIR system", "United States"),
    ("C", "Canadian FIR system", "Canada"),
    ("EB", "Belgian FIR system", "Belgium"),
    ("ED", "German FIR system", "Germany"),
    ("EF", "Finnish FIR system", "Finland"),
    ("EG", "United Kingdom FIR system", "United Kingdom"),
    ("EH", "Dutch FIR system", "Netherlands"),
    ("EI", "Irish FIR system", "Ireland"),
    ("EK", "Danish FIR system", "Denmark"),
    ("EN", "Norwegian FIR system", "Norway"),
    ("EP", "Polish FIR system", "Poland"),
    ("ES", "Swedish FIR system", "Sweden"),
    ("ET", "German FIR system", "Germany"),
    ("LA", "Albanian FIR system", "Albania"),
    ("LB", "Bulgarian FIR system", "Bulgaria"),
    ("LC", "Cyprus FIR system", "Cyprus"),
    ("LD", "Croatian FIR system", "Croatia"),
    ("LE", "Spanish FIR system", "Spain"),
    ("LF", "French FIR system", "France"),
    ("LG", "Greek FIR system", "Greece"),
    ("LH", "Hungarian FIR system", "Hungary"),
    ("LI", "Italian FIR system", "Italy"),
    ("LJ", "Slovenian FIR system", "Slovenia"),
    ("LK", "Czech FIR system", "Czech Republic"),
    ("LL", "Israeli FIR system", "Israel"),
    ("LM", "Maltese FIR system", "Malta"),
    ("LO", "Austrian FIR system", "Austria"),
    ("LR", "Romanian FIR system", "Romania"),
    ("LS", "Swiss FIR system", "Switzerland"),
    ("LT", "Turkish FIR system", "Turkey"),
    ("LU", "Moldovan FIR system", "Moldova"),
    ("LZ", "Slovak FIR system", "Slovakia"),
    ("DA", "Algerian FIR system", "Algeria"),
    ("DB", "Benin FIR system", "Benin"),
    ("DG", "Ghanaian FIR system", "Ghana"),
    ("DI", "Cote d'Ivoire FIR system", "Cote d'Ivoire"),
    ("DN", "Nigerian FIR system", "Nigeria"),
    ("DT", "Tunisian FIR system", "Tunisia"),
    ("DX", "Togolese FIR system", "Togo"),
    ("FA", "South African FIR system", "South Africa"),
    ("FB", "Botswana FIR system", "Botswana"),
    ("FC", "Republic of the Congo FIR system", "Republic of the Congo"),
    ("FD", "Eswatini FIR system", "Eswatini"),
    ("FE", "Central African Republic FIR system", "Central African Republic"),
    ("FG", "Equatorial Guinea FIR system", "Equatorial Guinea"),
    ("FH", "Saint Helena FIR system", "Saint Helena"),
    ("FI", "Mauritius FIR system", "Mauritius"),
    ("FJ", "British Indian Ocean Territory FIR system", "British Indian Ocean Territory"),
    ("FK", "Cameroonian FIR system", "Cameroon"),
    ("FL", "Zambian FIR system", "Zambia"),
    ("FM", "Madagascar FIR system", "Madagascar"),
    ("FN", "Angolan FIR system", "Angola"),
    ("FO", "Gabonese FIR system", "Gabon"),
    ("FP", "Sao Tome and Principe FIR system", "Sao Tome and Principe"),
    ("FQ", "Mozambican FIR system", "Mozambique"),
    ("FS", "Seychelles FIR system", "Seychelles"),
    ("FT", "Chadian FIR system", "Chad"),
    ("FV", "Zimbabwean FIR system", "Zimbabwe"),
    ("FW", "Malawian FIR system", "Malawi"),
    ("FX", "Lesotho FIR system", "Lesotho"),
    ("FY", "Namibian FIR system", "Namibia"),
    ("FZ", "DR Congo FIR system", "Democratic Republic of the Congo"),
    ("GO", "Senegalese FIR system", "Senegal"),
    ("DR", "Niger FIR system", "Niger"),
    ("HE", "Egyptian FIR system", "Egypt"),
    ("HK", "Kenyan FIR system", "Kenya"),
    ("HL", "Libyan FIR system", "Libya"),
    ("HR", "Rwandan FIR system", "Rwanda"),
    ("HS", "Sudanese FIR system", "Sudan"),
    ("HT", "Tanzanian FIR system", "Tanzania"),
    ("HU", "Ugandan FIR system", "Uganda"),
    ("LI", "Italian FIR system", "Italy"),
    ("OA", "Afghan FIR system", "Afghanistan"),
    ("OB", "Bahraini FIR system", "Bahrain"),
    ("OE", "Saudi FIR system", "Saudi Arabia"),
    ("OI", "Iranian FIR system", "Iran"),
    ("OJ", "Jordanian FIR system", "Jordan"),
    ("OK", "Kuwaiti FIR system", "Kuwait"),
    ("OL", "Lebanese FIR system", "Lebanon"),
    ("OM", "UAE FIR system", "United Arab Emirates"),
    ("OO", "Omani FIR system", "Oman"),
    ("OR", "Iraqi FIR system", "Iraq"),
    ("OS", "Syrian FIR system", "Syria"),
    ("OT", "Qatari FIR system", "Qatar"),
    ("PA", "Alaskan FIR system", "United States"),
    ("PH", "Hawaiian FIR system", "United States"),
    ("PJ", "Caribbean Netherlands FIR system", "Caribbean Netherlands"),
    ("RJ", "Japanese FIR system", "Japan"),
    ("RK", "South Korean FIR system", "South Korea"),
    ("RO", "Okinawa FIR system", "Japan"),
    ("RP", "Philippine FIR system", "Philippines"),
    ("SA", "Argentine FIR system", "Argentina"),
    ("SB", "Brazilian FIR system", "Brazil"),
    ("SC", "Chilean FIR system", "Chile"),
    ("SE", "Ecuadorian FIR system", "Ecuador"),
    ("SG", "Paraguayan FIR system", "Paraguay"),
    ("SK", "Colombian FIR system", "Colombia"),
    ("SL", "Bolivian FIR system", "Bolivia"),
    ("SM", "Surinamese FIR system", "Suriname"),
    ("SO", "French Guiana FIR system", "French Guiana"),
    ("SP", "Peruvian FIR system", "Peru"),
    ("SU", "Uruguayan FIR system", "Uruguay"),
    ("SV", "Venezuelan FIR system", "Venezuela"),
    ("SW", "Venezuelan FIR system", "Venezuela"),
    ("TA", "Turkish FIR system", "Turkey"),
    ("TB", "Turkish FIR system", "Turkey"),
    ("TI", "Costa Rican FIR system", "Costa Rica"),
    ("TJ", "Puerto Rico FIR system", "Puerto Rico"),
    ("TL", "Mexican FIR system", "Mexico"),
    ("TN", "Central American FIR system", "Guatemala"),
    ("TR", "Mexican FIR system", "Mexico"),
    ("TT", "Cuban FIR system", "Cuba"),
    ("TU", "Central American FIR system", "Belize"),
    ("TV", "Central American FIR system", "El Salvador"),
    ("UA", "Kazakh FIR system", "Kazakhstan"),
    ("UB", "Azerbaijani FIR system", "Azerbaijan"),
    ("UC", "Kyrgyz FIR system", "Kyrgyzstan"),
    ("UD", "Armenian FIR system", "Armenia"),
    ("UE", "Russian FIR system", "Russia"),
    ("UG", "Georgian FIR system", "Georgia"),
    ("UH", "Russian FIR system", "Russia"),
    ("UI", "Russian FIR system", "Russia"),
    ("UK", "Ukrainian FIR system", "Ukraine"),
    ("UL", "Russian FIR system", "Russia"),
    ("UM", "Belarusian FIR system", "Belarus"),
    ("UN", "Russian FIR system", "Russia"),
    ("UO", "Russian FIR system", "Russia"),
    ("UR", "Russian FIR system", "Russia"),
    ("US", "Russian FIR system", "Russia"),
    ("UT", "Tajik FIR system", "Tajikistan"),
    ("UU", "Russian FIR system", "Russia"),
    ("UW", "Russian FIR system", "Russia"),
    ("VA", "Indian FIR system", "India"),
    ("VC", "Sri Lankan FIR system", "Sri Lanka"),
    ("VD", "Cambodian FIR system", "Cambodia"),
    ("VE", "Indian FIR system", "India"),
    ("VG", "Bangladeshi FIR system", "Bangladesh"),
    ("VH", "Hong Kong FIR system", "Hong Kong"),
    ("VI", "Indian FIR system", "India"),
    ("VL", "Laotian FIR system", "Laos"),
    ("VM", "Macau FIR system", "Macau"),
    ("VN", "Nepalese FIR system", "Nepal"),
    ("VO", "Indian FIR system", "India"),
    ("VQ", "Bhutanese FIR system", "Bhutan"),
    ("VR", "Maldivian FIR system", "Maldives"),
    ("VT", "Thai FIR system", "Thailand"),
    ("VV", "Vietnamese FIR system", "Vietnam"),
    ("VY", "Myanmar FIR system", "Myanmar"),
    ("WA", "Indonesian FIR system", "Indonesia"),
    ("WB", "Malaysian FIR system", "Malaysia"),
    ("WI", "Indonesian FIR system", "Indonesia"),
    ("WM", "Malaysian FIR system", "Malaysia"),
    ("WS", "Singapore FIR system", "Singapore"),
    ("Y", "Australian FIR system", "Australia"),
    ("ZB", "Chinese FIR system", "China"),
    ("ZG", "Chinese FIR system", "China"),
    ("ZH", "Chinese FIR system", "China"),
    ("ZJ", "Chinese FIR system", "China"),
    ("ZK", "North Korean FIR system", "North Korea"),
    ("ZL", "Chinese FIR system", "China"),
    ("ZM", "Mongolian FIR system", "Mongolia"),
    ("ZS", "Chinese FIR system", "China"),
    ("ZU", "Chinese FIR system", "China"),
    ("ZW", "Chinese FIR system", "China"),
    ("ZY", "Chinese FIR system", "China"),
    ("RC", "Taiwan FIR system", "Taiwan"),
    ("NZ", "New Zealand FIR system", "New Zealand"),
)


def resolve_notam_location_context(location: str | None) -> tuple[str | None, str | None, str | None]:
    if not isinstance(location, str):
        return None, None, None

    icao_code = location.strip().upper()
    if not icao_code:
        return None, None, None

    exact = EXACT_LOCATION_CONTEXT.get(icao_code)
    if exact is not None:
        fir_name, country_name = exact
        return icao_code, fir_name, country_name

    for prefix, fir_name, country_name in PREFIX_LOCATION_CONTEXT:
        if icao_code.startswith(prefix):
            return icao_code, fir_name, country_name

    return icao_code, None, None
